config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'

  get  '/import', to: 'blogs#import'
  post '/import', to: 'blogs#create'
  get  '/export', to: 'blogs#export'
  get 'up' => 'rails/health#show', as: :rails_health_check

  get  '/:slug', to: 'blogs#show', as: :show_blog

  resources :blogs, only: [:index, :update], param: :slug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  before_validation :generate_slug, on: :create

  validates :slug, presence: true, uniqueness: true
  validates_presence_of :author, :slug, :content

  encrypts :content # Enables Rails encryption

  def to_param
    slug
  end

  def content_base64
    Base64.encode64(content)
  end

  private

  def generate_slug
    self.slug ||= build_slug
  end

  def build_slug
    "#{find_tree_first_word}-#{SecureRandom.hex}"
  end

  def find_tree_first_word
    self.content.split(" ")[0..2].join("-").downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show update ]
  before_action :set_blogs, only: %i[ index export ]

  def index
    @blogs = Blog.all
  end

  def show
  end

  def create
    result = Blogs::ImportService.call(params[:file])

    if result[:success]
      flash.now[:notice] = result[:message]
    else
      flash.now[:error] = result[:message]
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "import_response",
          partial: "blogs/import_response"
        )
      end
    end
  end

  def update
    if @blog.update(blog_params)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("main_content", partial: "blogs/main_content", locals: { blog: @blog }),
            turbo_stream.replace("blog_error", partial: "blogs/error", locals: { blog: @blog })
          ]
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("blog_error", partial: "blogs/error", locals: { blog: @blog })
          ]
        end
      end
    end
  end

  def export
    # can be implement cache later
    render json: BlogBlueprint.render(@blogs)
  end

  def import
  end

  private

  def set_blog
    @blog = Blog.find_by(slug: params[:slug])
  end

  def set_blogs
    @blogs = Blog.all
  end

  def blog_params
    params.require(:blog).permit([:author, :content])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="content_element" class="items-center text-gray-500 text-sm mt-4" data-blog-target="content">
  <div data-blog-target="content">
    Author by <%= blog.author %> / created at <%= blog.created_at.strftime('%d/%m/%Y %H:%M:%S') %>

    <% if context == 'show_page' %>
      <div class="mt-5 p-4 w-100">
        <%= blog.content.html_safe %>
      </div>
    <% else %>
      <div class="line-clamp-3 max-w-[80ch] break-words">
        <%#= use strip_tags in content have image, that image should not show in index page %>
        <%= strip_tags(blog.content.html_safe) %>
      </div>

      <div class="flex justify-end mt-2">
        <%= link_to "Read more >>",
                    show_blog_path(blog),
                    class: "text-sm text-blue-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/_error.html.erb
<turbo-frame id="blog_error">
  <% if @blog.errors.any? %>
    <div class="mt-4 p-3 bg-transparent text-red-700 rounded-lg border border-red-500">
      <ul class="list-disc pl-5">
        <% @blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</turbo-frame>

app/views/blogs/_form.html.erb
<turbo-frame id="blog_form">
  <div id="form_element" data-blog-target="form" class="<%= hidden_form ? 'hidden' : '' %>">
    <%= form_with model: blog,
                  url: blog_path(blog),
                  data: { turbo: true } do |f| %>

      <div class="mt-3">
        <%= f.label :author, class: 'block text-white text-sm font-bold mb-2' %>
        <%= f.text_field :author, class: "w-full p-2 bg-gray-800 text-white placeholder-gray-400 border border-gray-600 rounded-md" %>
      </div>

      <div class="mt-3">
        <%= f.label :content, class: 'block text-white text-sm font-bold mb-2' %>
        <div data-controller="tinymce">
          <%= f.text_area :content,
                          class: "tinymce",
                          rows: 40,
                          id: "tinymce-editor",
                          data: {"tinymce-target": 'textarea'}
          %>
        </div>
      </div>

      <div class="mt-2 space-x-2 text-right">
        <button type="button"
                class="bg-gray-500 px-4 py-2 rounded text-white"
                data-action="click->blog#cancel">
          Cancel
        </button>

        <%= f.submit "Save",
                     class: "bg-orange-500 px-4 py-2 rounded text-white"
        %>
      </div>
    <% end %>
  </div>
</turbo-frame>

app/views/blogs/_form_wrapper.html.erb
<div class="mt-5 p-5">
  <%= render 'error' %>
  <%= render 'form', hidden_form: true %>
</div>

app/views/blogs/_import_response.html.erb
<turbo-frame id="import_response">
  <% if flash[:error].present? %>
    <div class="mt-4 p-3 bg-transparent text-red-700 rounded-lg border border-red-500">
      <%= flash[:error] %>
    </div>
  <% end %>

  <% if flash[:notice].present? %>
    <div class="mt-4 p-3 bg-transparent text-green-700 rounded-lg border border-green-500">
      <%= flash[:notice] %>
    </div>
  <% end %>
</turbo-frame>

app/views/blogs/_main_content.html.erb
<turbo-frame id="blog_content">
  <%= render "blog", blog: blog, context: 'show_page' %>
</turbo-frame>

<div class="mt-5 p-5">
  <%= render 'error' %>
  <%= render 'form', blog: blog, hidden_form: true %>
</div>

app/views/blogs/import.html.erb
<div class="bg-neutral-900 text-neutral-100 p-6 rounded-lg shadow-lg">
  <h1 class="text-2xl font-bold mb-4">Import Blog Posts</h1>

  <%= form_with url: import_path,
                multipart: true,
                method: 'POST',
                data: { turbo: true },
                html: { class: 'space-y-4' } do |form| %>
    <div class="bg-neutral-800 p-4 rounded-lg border border-neutral-700">
      <%= form.label :file, "JSON File", class: "block text-lg font-medium text-neutral-300 mb-2" %>
      <%= form.file_field :file, class: "block w-full text-sm text-neutral-300 bg-neutral-700 border border-neutral-600 rounded-lg cursor-pointer focus:outline-none" %>
    </div>

    <div id="import_response">
      <%= render 'import_response' %>
    </div>

    <div class="mt-5 text-right">
      <%= link_to 'Cancel',
                  root_path,
                  class: 'btn bg-gray-500 px-4 py-2 rounded text-white'
      %>

      <%= form.submit "Create Blog",
                      class: "px-4 py-2 font-semibold text-white bg-orange-600 hover:bg-orange-500 rounded-lg shadow-md transition-all" %>
    </div>
  <% end %>
</div>

app/views/blogs/index.html.erb
<div class="w-full">
  <div id="blogs" class="flex-1">
    <div class="space-y-4 mt-3">
      <% if @blogs.any? %>
        <% @blogs.each do |blog| %>
          <div class="p-4 rounded-lg shadow max-w-[75ch]">
            <%= render blog, context: 'index_page' %>
          </div>

          <div class="px-3 mt-3">
            <hr />
          </div>
        <% end %>
      <% else %>
        <p class="text-center my-10">No blogs found.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="mt-2">
  <%= link_to '<< Back to Home', '/', class: 'text-sm text-blue-500' %>
</div>

<div class="mt-3 w-full" data-controller="blog">
  <div class="flex">
    <div class="w-2/3">
      <h1 class="font-bold text-4xl">
        <%= @blog.slug %>
      </h1>
    </div>

    <div class="w-1/3 text-right mr-5">
      <button
        class="bg-orange-500 px-4 py-2 rounded-full text-white font-medium hover:bg-orange-600"
        data-action="click->blog#edit"
      >
        Edit
      </button>
    </div>
  </div>

  <div id="main_content">
    <%= render "main_content", blog: @blog %>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="w-64 bg-[#1a1a1b] text-white h-screen p-4 space-y-4 min-h-auto">
  <!-- Home & Popular -->
  <div>
    <h2 class="text-gray-400 text-sm font-semibold mb-2">FEEDS</h2>
    <ul class="space-y-2">
      <li>
          <span>
            <%= link_to 'Home' , '/', class: 'flex items-center space-x-2 p-2 rounded-lg hover:bg-[#272729]' %>
          </span>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_topbar.html.erb
<div class="bg-[#1a1a1b] text-white px-4 py-2 flex items-center justify-between shadow-md">
  <div class="flex items-center space-x-2">
    <span class="text-xl font-semibold"><%= link_to 'Blogdit', '/' %></span>
  </div>

  <div class="flex-1 mx-4">
    <input type="text"
           placeholder="Just for beautiful, Can't search anything"
           class="w-full bg-[#272729] text-white px-4 py-2 rounded-full focus:outline-none focus:ring focus:ring-orange-500">
  </div>

  <div class="flex items-center space-x-4">
    <%= link_to import_path do %>
      <button class="btn bg-orange-500 px-4 py-2 rounded-full text-white font-medium hover:bg-orange-600 disabled:bg-gray-500"
        <%= current_page?(import_path) ? 'disabled' : '' %>
      >
        Import
      </button>
    <% end %>

    <%= link_to 'Export',
                export_path,
                target: "_blank",
                class: 'btn bg-orange-500 px-4 py-2 rounded-full text-white font-medium hover:bg-orange-600'
    %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Blog Encrypted Content" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= tinymce_assets %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body class="bg-black text-white font-mono">
    <%= render 'layouts/topbar' %>

    <div class="flex">

      <div class="w-64">
        <%= render 'layouts/sidebar' %>
      </div>

      <div class="flex-1 p-4">
        <%= yield %>
      </div>
    </div>
  </body>
</html>